spring:
  datasource:
    # 连接MySQL配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.1:3306/databaseName  # 这里修改为您的MySQL数据库连接地址
    username: database-user-name  # 这里修改为您的MySQL数据库用户名
    password: database-user-password  # 这里修改为您的MySQL数据库密码

  mail:
    host: smtp.qq.com
    port: 587
    username: yourEmail@qq.com  # 这里修改为您的QQ邮箱名称（推荐是企业账号，用于发送验证短信）
    password: yourEmailSMTP  # 这里修改为您的QQ邮箱SMTP授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: 192.168.1.1  # 这里修改为您的Redis数据库连接地址
      port: 6379  # 这里修改为您的Redis数据库端口号
      password: yourRedisPassword  # 这里修改为您的Redis数据库密码

mybatis:
  mapper-locations: classpath*:mapper/*.xml # 指定XML映射配置文件路径
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出MySQL操作日志


# 配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: info